spring:
    jpa:
        show-sql: true
        # hibernate.ddl-auto: create-drop
    datasource:
        url: jdbc:h2:mem:database
        username: sa
        password: password
    h2:
        console:
            enabled: true
