vaadin:
    launch-browser: true
spring:
    application:
        name: alerts-vaadin

    jpa:
        show-sql: true
        hibernate.ddl-auto: create-drop
    datasource:
        url: jdbc:h2:file:./database
        username: sa
        password: password
    h2:
        console:
            enabled: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: antoine.haz@gmail.com
        password: ${GOOGLE_PASSWORD}
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.debug: true
