spring:
    jpa:
        show-sql: true
        hibernate.ddl-auto: create-drop
    datasource:
        url: ${DATABASE_URL}
        username: sa
        password: password
    h2:
        console:
            enabled: true
